NexusCraftingConfig = {
    verticalSlice = {
        enabled = true,
        stationId = 'mechanic_bench',
        recipeId = 'repairkit_basic',
        outputItem = 'repairkit',
        outputCount = 1,
        job = 'mechanic',
        minimumGrade = 0,
        reserveRateLimitMs = 1500,
    },
    debug = false,
    command = 'crafting',
    nearestCommand = 'craftnear',
    editorCommand = 'crafteditor',
    interactDistance = 3.0,
    rateLimitBucket = 'crafting',
    illegalAccess = {
        minimumCriminalReputation = 2,
    },
    criminalProgression = {
        enabled = true,
        sensitiveOnly = true,
        xpMultiplier = 0.25,
        reputation = 1,
    },

    sceneCore = {
        enabled = true,
        fallback = 'craft_civil',
        categories = {
            civil = 'craft_civil',
            mechanic = 'craft_mechanic',
            illegal = 'craft_illegal',
            ems = 'craft_medical',
            police = 'craft_police',
        },
    },

    sensitiveAlert = {
        enabled = true,
        policeJobs = { police = true, bcso = true, sasp = true },
        cooldownSeconds = 120,
    },

    defaultAccess = {
        type = 'public',
        category = 'civil',
        recipes = { 'bandage_basic', 'lockpick_basic', 'radio_basic', 'repairkit_basic' },
        model = 'gr_prop_gr_bench_04b',
    },

    editor = {
        ace = 'nexus.crafting.admin',
        defaultSize = vector3(1.6, 1.2, 1.2),
        defaultHeading = 0.0,
        defaultLabel = 'Mesa de trabajo',
        placementDistance = 2.2,
        models = {
            { label = 'Workbench tecnico', value = 'gr_prop_gr_bench_04b' },
            { label = 'Banco de herramientas', value = 'prop_tool_bench02' },
            { label = 'Mesa industrial', value = 'prop_table_03' },
        },
    },

    worldUi = {
        enabled = true,
        drawDistance = 14.0,
        interactDistance = 5.0,
        markerScale = vector3(1.25, 0.45, 0.08),
        color = { r = 0, g = 210, b = 255, a = 160 },
    },

    categories = {
        civil = { label = 'Civil', variant = 'civil' },
        mechanic = { label = 'Mecanico', variant = 'business' },
        illegal = { label = 'Mercado negro', variant = 'illegal' },
        ems = { label = 'EMS', variant = 'ems' },
        police = { label = 'Policia', variant = 'police' },
    },

    stations = {
        public_workbench = {
            label = 'Mesa de trabajo',
            type = 'public',
            category = 'civil',
            coords = vector3(472.31, -1310.72, 29.22),
            size = vector3(1.6, 1.2, 1.2),
            heading = 25.0,
            recipes = { 'bandage_basic', 'lockpick_basic', 'radio_basic', 'repairkit_basic' },
        },
        mechanic_bench = {
            label = 'Banco mecanico',
            type = 'job',
            mode = 'mechanic',
            category = 'mechanic',
            job = 'mechanic',
            coords = vector3(-211.61, -1324.64, 30.89),
            size = vector3(1.8, 1.2, 1.2),
            heading = 70.0,
            recipes = { 'repairkit_basic' },
        },
        ems_bench = {
            label = 'Mesa clinica EMS',
            type = 'job',
            category = 'ems',
            job = 'ambulance',
            coords = vector3(310.52, -597.88, 43.28),
            size = vector3(1.6, 1.2, 1.2),
            heading = 70.0,
            recipes = { 'bandage_basic', 'painkillers_pack', 'ifak_pack' },
        },
        police_armory_bench = {
            label = 'Mesa tecnica policial',
            type = 'jobs',
            category = 'police',
            jobs = { police = 0, bcso = 0, sasp = 0 },
            coords = vector3(482.43, -995.22, 30.69),
            size = vector3(1.6, 1.2, 1.2),
            heading = 90.0,
            recipes = { 'evidence_bag_pack', 'handcuffs_service', 'radio_police' },
        },
        illegal_bench = {
            label = 'Mesa clandestina',
            type = 'illegal',
            category = 'illegal',
            coords = vector3(1395.43, 3608.87, 38.94),
            size = vector3(1.6, 1.2, 1.2),
            heading = 20.0,
            recipes = { 'lockpick_basic', 'scanner_shell', 'drill_kit', 'thermite_mix' },
        },
    },

    recipes = {
        bandage_basic = {
            label = 'Vendaje improvisado',
            category = 'civil',
            output = { item = 'bandage', count = 1 },
            ingredients = {
                { item = 'plastic', count = 1 },
                { item = 'rubber', count = 1 },
            },
            duration = 4500,
            requiredLevel = 1,
            xp = 35,
            reputation = 1,
        },
        lockpick_basic = {
            label = 'Ganzua basica',
            category = 'illegal',
            blueprint = 'blueprint_lockpick',
            hiddenUntilLevel = 1,
            hiddenUntilReputation = 0,
            risk = { policeAlertChance = 8 },
            sensitive = true,
            output = { item = 'lockpick', count = 1 },
            ingredients = {
                { item = 'metalscrap', count = 2 },
                { item = 'steel', count = 1 },
            },
            duration = 6500,
            requiredLevel = 1,
            xp = 55,
            reputation = 1,
        },
        radio_basic = {
            label = 'Radio civil',
            category = 'civil',
            output = { item = 'radio', count = 1 },
            ingredients = {
                { item = 'plastic', count = 2 },
                { item = 'glass', count = 1 },
                { item = 'aluminum', count = 1 },
            },
            duration = 7000,
            requiredLevel = 2,
            xp = 70,
            reputation = 1,
        },
        repairkit_basic = {
            label = 'Kit de reparacion',
            category = 'mechanic',
            output = { item = 'repairkit', count = 1 },
            ingredients = {
                { item = 'metalscrap', count = 3 },
                { item = 'iron', count = 2 },
                { item = 'plastic', count = 2 },
            },
            duration = 8500,
            requiredLevel = 1,
            xp = 0,
            reputation = 0,
        },
        toolkit_parts = {
            label = 'Piezas de taller',
            category = 'mechanic',
            output = { item = 'metalscrap', count = 2 },
            ingredients = {
                { item = 'steel', count = 1 },
                { item = 'aluminum', count = 1 },
            },
            duration = 5000,
            requiredLevel = 1,
            xp = 40,
            reputation = 1,
        },
        advanced_repairkit = {
            label = 'Kit avanzado de reparacion',
            category = 'mechanic',
            blueprint = 'blueprint_advanced_repairkit',
            hiddenUntilLevel = 4,
            hiddenUntilReputation = 3,
            output = { item = 'advancedrepairkit', count = 1 },
            ingredients = {
                { item = 'repairkit', count = 1 },
                { item = 'steel', count = 2 },
                { item = 'rubber', count = 2 },
            },
            duration = 11000,
            requiredLevel = 5,
            xp = 140,
            reputation = 3,
        },
        painkillers_pack = {
            label = 'Paquete de analgesicos',
            category = 'ems',
            output = { item = 'painkillers', count = 2 },
            ingredients = {
                { item = 'plastic', count = 1 },
                { item = 'rubber', count = 1 },
            },
            duration = 5500,
            requiredLevel = 2,
            xp = 65,
            reputation = 1,
        },
        ifak_pack = {
            label = 'IFAK clinico',
            category = 'ems',
            output = { item = 'ifaks', count = 1 },
            ingredients = {
                { item = 'bandage', count = 2 },
                { item = 'plastic', count = 2 },
                { item = 'rubber', count = 1 },
            },
            duration = 9000,
            requiredLevel = 4,
            xp = 120,
            reputation = 2,
        },
        evidence_bag_pack = {
            label = 'Pack bolsas de evidencia',
            category = 'police',
            output = { item = 'empty_evidence_bag', count = 5 },
            ingredients = {
                { item = 'plastic', count = 2 },
            },
            duration = 4500,
            requiredLevel = 1,
            xp = 35,
            reputation = 1,
        },
        handcuffs_service = {
            label = 'Esposas de servicio',
            category = 'police',
            output = { item = 'handcuffs', count = 1 },
            ingredients = {
                { item = 'steel', count = 3 },
                { item = 'metalscrap', count = 2 },
            },
            duration = 8500,
            requiredLevel = 3,
            xp = 95,
            reputation = 2,
        },
        radio_police = {
            label = 'Radio policial',
            category = 'police',
            output = { item = 'radio', count = 1 },
            ingredients = {
                { item = 'electronickit', count = 1 },
                { item = 'plastic', count = 2 },
            },
            duration = 8500,
            requiredLevel = 4,
            xp = 110,
            reputation = 2,
        },
        scanner_shell = {
            label = 'Carcasa electronica',
            category = 'illegal',
            output = { item = 'glass', count = 1 },
            ingredients = {
                { item = 'plastic', count = 2 },
                { item = 'aluminum', count = 1 },
            },
            duration = 7000,
            requiredLevel = 2,
            xp = 65,
            reputation = 2,
        },
        drill_kit = {
            label = 'Taladro preparado',
            category = 'illegal',
            blueprint = 'blueprint_drill',
            hiddenUntilLevel = 5,
            hiddenUntilReputation = 8,
            risk = { policeAlertChance = 25 },
            sensitive = true,
            output = { item = 'drill', count = 1 },
            ingredients = {
                { item = 'metalscrap', count = 5 },
                { item = 'steel', count = 3 },
                { item = 'electronickit', count = 1 },
            },
            duration = 12500,
            requiredLevel = 6,
            xp = 175,
            reputation = 4,
        },
        thermite_mix = {
            label = 'Carga de thermite',
            category = 'illegal',
            blueprint = 'blueprint_thermite',
            hiddenUntilLevel = 6,
            hiddenUntilReputation = 10,
            risk = { policeAlertChance = 35 },
            sensitive = true,
            output = { item = 'thermite', count = 1 },
            ingredients = {
                { item = 'aluminum', count = 3 },
                { item = 'plastic', count = 3 },
                { item = 'electronickit', count = 1 },
            },
            duration = 14000,
            requiredLevel = 8,
            xp = 220,
            reputation = 5,
        },
    },
}
