CREATE TABLE IF NOT EXISTS nexus_dispatch_alerts (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    alert_type VARCHAR(64) NOT NULL DEFAULT 'generic',
    title VARCHAR(96) NOT NULL DEFAULT 'Incidente',
    message VARCHAR(255) NOT NULL DEFAULT '',
    coords_x DOUBLE NULL,
    coords_y DOUBLE NULL,
    coords_z DOUBLE NULL,
    zone_id VARCHAR(64) NULL,
    source_resource VARCHAR(64) NULL,
    source_player INT NULL,
    citizenid VARCHAR(64) NULL,
    gang_name VARCHAR(64) NULL,
    risk INT NOT NULL DEFAULT 0,
    priority INT NOT NULL DEFAULT 1,
    status VARCHAR(24) NOT NULL DEFAULT 'open',
    assigned_citizenid VARCHAR(64) NULL,
    assigned_name VARCHAR(96) NULL,
    closed_by_citizenid VARCHAR(64) NULL,
    closed_by_name VARCHAR(96) NULL,
    closed_at TIMESTAMP NULL,
    close_result VARCHAR(64) NULL,
    close_notes TEXT NULL,
    operational_notes TEXT NULL,
    ais_case_id INT NULL,
    ais_case_number VARCHAR(64) NULL,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_dispatch_created (created_at),
    INDEX idx_dispatch_status (status),
    INDEX idx_dispatch_type (alert_type),
    INDEX idx_dispatch_zone (zone_id),
    INDEX idx_dispatch_gang (gang_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS nexus_dispatch_units (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    alert_id INT UNSIGNED NOT NULL,
    citizenid VARCHAR(64) NOT NULL,
    officer_name VARCHAR(96) NOT NULL,
    unit_status VARCHAR(24) NOT NULL DEFAULT 'assigned',
    assigned_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uniq_dispatch_unit (alert_id, citizenid),
    INDEX idx_dispatch_units_alert (alert_id),
    INDEX idx_dispatch_units_status (unit_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
